name: "Cleanup After Branch Deletion"
author: "Jeremy Juventin"
description: This GitHub Action cleans up rBigQuery schemas and Dataform workspaces after a branch is deleted.
branding:
  icon: database
  color: blue

inputs:
  project_id:
    description: |-
      ID of the project where your Dataform workspace is located.
    required: true
  dataform_repo_name:
    description: |-
      Name of the Dataform repository.
    required: true
  dataform_repo_location:
    description: |-
      Location of the Dataform repository. For example, `us-central1`.
    required: true
  SA_KEY:
    description: |-
      Service account key used to authenticate with GCP (JSON format).
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "BRANCH_NAME=${{ github.event.ref }}" >> $GITHUB_ENV
        echo "SA_KEY=${{ inputs.SA_KEY }}" >> $GITHUB_ENV

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.SA_KEY }}

    - name: Delete BigQuery Schemas
      shell: bash
      run: |
        TABLE_SUFFIX="_${BRANCH_NAME//-/_}"
        echo "Deleting schemas with suffix $TABLE_SUFFIX in project ${{ inputs.project_id }}"
        bq --project_id="${{ inputs.project_id }}" ls --format=json | jq -r ".[] | select(.datasetReference.datasetId | endswith(\"$TABLE_SUFFIX\")).datasetReference.datasetId" | while read -r dataset_id; do
          echo "Deleting dataset: $dataset_id"
          bq --project_id="${{ inputs.project_id }}" rm -r -f -d "$dataset_id"
        done

    - name: Delete Dataform Workspace
      shell: bash
      run: |
        echo "Deleting Dataform workspace: $BRANCH_NAME"
        curl -X DELETE "https://dataform.googleapis.com/v1beta1/projects/${{ inputs.project_id }}/locations/${{ inputs.dataform_repo_location }}/repositories/${{ inputs.dataform_repo_name }}/workspaces/$BRANCH_NAME" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)"